# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JhnnyK.com
email: jhnnyk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Family man, developer, mountain ultra trail runner - John Knotts
baseurl: "" # the subpath of your site, e.g. /blog
url: http://jhnnyk.github.io # the base hostname & protocol for your site
twitter_username: jhnnyk
github_username:  jhnnyk

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate

paginate: 5

# Permalinks
permalink: /:title